version: '3.3'
services:  
  postgres:
    platform: 'linux/amd64'
    image: postgres:latest
    container_name: codewithmuh-backend-postgres-local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5437:5432'
    volumes:
      - codewithmuh-backend-postgres-local:/var/lib/postgresql/data/

  backend:
    platform: 'linux/amd64'
    image: codewithmuh-backend-django:local
    container_name: codewithmuh-backend-django-local
    build:
      context: ../../
      dockerfile: ./build-process/codewithmuh-backend/docker-backend-django/Dockerfile
      args:
        APP_ENVIRONMENT: 'Local'
    volumes:
      - ../../:/home/codewithmuh-backend
    ports:
      - '8080:8080'
    env_file:
      - ./local.codewithmuh-backend.env
    depends_on:
      - postgres

volumes:
  codewithmuh-backend-postgres-local:
  esdata:

